### ISSUE TITLE
Connection refused issue

### ISSUE THREAD

**Issue by justwalking2017** [moosa-r/rbioapi#10]
Hi there,

Last month I run rbioapi smoothly on my laptop. But for last four days, every time I run rba_panther_enrich() I got an error even use the test input:

 rba_panther_enrich(genes = c("p53", "BRCA1", "cdk2", "Q99835", "CDC42",
                              "CDK1", "KIF23", "PLK1", "RAC2", "RACGAP1"),
                    organism = 9606, annot_dataset = "GO:0008150", cutoff = 0.01)

Performing over-representation enrichment analysis of 10 input genes of organism 9606 against GO:0008150 datasets.
**Error: Failed to connect to www.pantherdb.org port 80: Connection refused**

R is 4.2.2 and rbioapi is 0.7.9. 

Have I been blocked? The analysis is somehow a bit of a hurry. Any comments and suggestions appreciate!

Thanks,
Bohu

**Comment by moosa-r** [comment]
Hi Bohu,

Thank you for reporting this issue.
It is because PANTHER moved their API URL to HTTPS. I made a [minor fix ](https://github.com/moosa-r/rbioapi/commit/abbfcc59250c10fff1e0d0db86062754bc2cf104) to reflect this change.
You can reinstall rbioapi with the latest fix using the following commands: (I will submit it to CRAN when some changes accumulate)

````
install.packages("remotes")
remotes::install_github("moosa-r/rbioapi")
````

Best,
Moosa

**Comment by justwalking2017** [comment]
Hi Moosa,

It works. Appreciate your prompt help！


Best Regards,
Bohu
