### ISSUE TITLE
The server returned HTTP Status '405'

### ISSUE THREAD

**Issue by marikopal** [moosa-r/rbioapi#11]
Hi,

Thanks for the great API, it is extremely useful for my research. 

I am trying to run some miRNA enrichment with the following code:

```
rba_mieaa_enrich(test_set =deg_up,
                             mirna_type = "mature",
                             test_type = "ORA",
                             species = "hsa")
```

But for the past few days it just gives back an error:

```
 -- Step 1/3: Submitting Enrichment analysis request:
Submitting ORA enrichment request for 1 miRNA IDs of species Homo sapiens to miEAA servers.
Error: The server returned HTTP Status '405' (Redirection: Method Not Allowed).
```

I tried to update `rbioapi` and also restrict the enrichment to certain categories, but all the same. 
I would greatly appreciate some help to make it work again.

Best regards,
Mariko

**Comment by moosa-r** [comment]
Dear Mariko,
Thank you for reporting this issue.

This is because MiEAA changed their API root address a few weeks ago. I made a [minor fix](https://github.com/moosa-r/rbioapi/commit/e60dc32e3ce92931a20927504b77d9a0c154fa7f) to reflect this change. But I haven't submitted the latest version to CRAN yet, since I'm waiting for some changes to accumulate.

Meanwhile, please install the latest -developmental- version from the GitHub repository:

````
install.packages("remotes")
remotes::install_github("moosa-r/rbioapi")
````

Kind regards,
Moosa
