### ISSUE TITLE
Problem with the Panther serve

### ISSUE THREAD

**Issue by ElsaWassmer** [moosa-r/rbioapi#12]
Dear Moosa, 

I was using the rbioapi packages to access the Panther server, and until today it was fine. However I got this error today, even with the example provided by the rbioapi website:

> rba_panther_enrich(genes = c("p53", "BRCA1", "cdk2", "Q99835", "CDC42",
+                              "CDK1", "KIF23", "PLK1", "RAC2", "RACGAP1"),
+                    organism = 9606, annot_dataset = "GO:0008150",
+                    cutoff = 0.01)
Performing over-representation enrichment analysis of 10 input genes of organism 9606 against GO:0008150 datasets.
Error in .rba_skeleton(input_call) : 
  Internal Error: Failed to parse the server's response. This is probably because the server has changed the response format. Please report this bug to us: 
 Error in jsonlite::flatten(x$result) : is.data.frame(x) is not TRUE

Do you know if it will be corrected soon?

Best, 
Elsa

**Comment by moosa-r** [comment]
Dear Elsa,
Thank you for reporting this issue. Since rbioapi is an unofficial implementation, I can only be aware of changes in the supported web services after their deployment.

I've made minor fixes to reflect the recent changes in PANTHER's API in the past few weeks.
You can reinstall rbioapi with the latest fix using the following commands: (I will submit it to CRAN when some changes accumulate)

````
install.packages("remotes")
remotes::install_github("moosa-r/rbioapi")
````

Hopefully, this will solve your problem. The above example works just fine on my end.

Best,
Moosa
