### ISSUE TITLE
Issue with pantherDB API

### ISSUE THREAD

**Issue by AudreyGibert** [moosa-r/rbioapi#8]
Hi, 
I launched this morning a code that was working yesterday and get a message asking to report it to you, Here is an example of command giving the error message :
```R
rba_panther_enrich(genes = c("PRMT6", "GDAP2", "WDR3",  "TBX15", "WARS2", "HAO2"), organism = 9606, annot_dataset = 'GO:0048241')
Performing over-representation enrichment analysis of 6 input genes of organism 9606 against GO:0048241 datasets.

Error in .rba_skeleton(input_call): Internal Error: Failed to parse the server's response. This is probably because the server has changed the response format. Please report this bug to us: 
 Error in jsonlite::flatten(x$result) : is.data.frame(x) n'est pas TRUE
```
Thank you for your help,
Audrey

**Comment by moosa-r** [comment]
Hi,

This is because you provided a non-supported value for the annot_dataset argument. Please run `rba_panther_info(what = "datasets")` to see the available options.

P.S.:  The CRAN version is a bit outdated. I updated PANTHER's response parser (https://github.com/moosa-r/rbioapi/issues/4), so in the current version from this repository, you will get the following response, which is more informative:

````
rba_panther_enrich(genes = c("PRMT6", "GDAP2", "WDR3",  "TBX15", "WARS2", "HAO2"), organism = 9606, annot_dataset = 'GO:0048241')

$search
$search$error
[1] "Error ontology type not supported"

$search$search_type
[1] "overrepresentation"
````
Best,
Moosa
